language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install -U importlib_metadata
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest tests --cov-report term --cov=junix.junix -vv
