language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -U -r requirements.txt
  - python setup.py install
script:
  - pytest tests --cov-report term --cov=junix.junix -vv
