name: Run Python Tests
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python setup.py develop
          pytest
